##
## Dependabot. Only check for security issues, as this repository needs to be as stable
## as possible during academic years.
##

version: 2
updates:

# Check for changes to GitHub actions on a monthly basis. This should keep the repo
# updated, without being too annoying
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

# Ignore updates to Python pip dependencies. This will turn off all except security
# alerts
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
