site_name: uREST MicroPython Library

theme:
  name: readthedocs

extra_css:
  - css/extra.css

plugins:
  - autorefs
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            heading_level: 2
            separate_signature: True
            docstring_section_style: list
            show_root_heading: True
            show_signature_annotations: True
            show_category_heading: True
            show_source: True
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - smarty

nav:
  - Home: 'index.md'
  - 'Tutorials':
    - 'Pico Network Server': 'tutorials/pico_server.md'
    - 'A Simple Echo Server': 'tutorials/client_test.md'
  - 'How-To':
    - 'Creating a Network Server': 'how_to/api_server.md'
    - 'Set-Up the Pico Board': 'how_to/pico_setup.md'
    - 'Testing the Library': 'how_to/run_tests.md'
  - 'Reference':
    - 'Building an API for Network Clients': 'ref/api.md'
    - 'The uREST Server Implementation': 'ref/http.md'
    - 'Library Exceptions': 'ref/exceptions.md'
    - 'Library Utilities': 'ref/utils.md'
  - 'Background':
    - 'REST APIs': 'background/rest.md'

watch:
  - urest
