site_name: uREST MicroPython Library

theme:
  name: readthedocs

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            heading_level: 4

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - 'Tutorials':
    - 'Pico Network Server': 'tutorials/pico_server.md'
    - 'Creating a Client': 'tutorials/client_test.md'
  - 'How-To':
    - 'Set-Up the Pico Board': 'how_to/pico_setup.md'
    - 'Testing the Library': 'how_to/run_tests.md'
  - 'Reference':
    - 'Creating an API': 'ref/api.md'
    - 'Serving the API': 'ref/http.md'
  - 'Background':
    - 'REST APIs': 'background/rest.md'
